version: "3.1"

services:
  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"
    environment:
      POSTGRES_DB: forms
      POSTGRES_USER: forms
      POSTGRES_PASSWORD: forms
#      ROCKET_PROFILE_URL: "http://localhost:8001/profile" # users

  # profiles_api:
  #   image: kennycallado/uv-questions_api-profiles:v0.1-amd64
  #   ports:
  #     - "8001:8000"
  #   expose:
  #     - "8001:8000"
  #   environment:
  #     - ROCKET_DATABASES={question={url="postgres://users:users@database/users"}}
  #     - ROCKET_ADDRESS="0.0.0.0"
  #     - ROCKET_PORT=8000
