#
# export WORKING_URL=questions.kennycallado.dev
# export WORKING_URL=localhost:8000

# 1 admin eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxLCJkZXBlbmRzX29uIjoxLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4ifSwidXNlcl90b2tlbiI6IjBiZGJkZTk0LTY1ZjctNGVjMC1iNWI0LWMwYzE0ZDQ0MGEyZiJ9LCJpYXQiOjE2Nzc2Njg1NzAsImV4cCI6MTY3ODI3MzM3MH0.LyKLztGQ2rBMOlomvxoqDCJR9BmNi7UW0inp3rGYYu4
# 2 coord eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoyLCJkZXBlbmRzX29uIjoxLCJyb2xlIjp7ImlkIjoyLCJuYW1lIjoiY29vcmQifSwidXNlcl90b2tlbiI6Ijk0YmRiZDg0LTRiNDktNDZjOC04NDM3LTdkMzgzYTVlMThmZCJ9LCJpYXQiOjE2Nzc2Njg3ODksImV4cCI6MTY3ODI3MzU4OX0.0NBOoGltz22a-bOrAvfSkIcuMfxtPSh2-LgtvmODdgA
# 4 thera eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjo0LCJkZXBlbmRzX29uIjoxLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGhlcmEifSwidXNlcl90b2tlbiI6IjY2ODZhZDAyLTUwYTEtNDE1Ni05YTAzLTlmNmIxMmQyMzFhMSJ9LCJpYXQiOjE2Nzc2Njg4MDQsImV4cCI6MTY3ODI3MzYwNH0.L2MmHEsJY9DMdxqaa3ziitYPp4n9SE8gSkL0Znm7iSY
# 7 user eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjo3LCJkZXBlbmRzX29uIjoxLCJyb2xlIjp7ImlkIjo0LCJuYW1lIjoidXNlciJ9LCJ1c2VyX3Rva2VuIjoiYWE3NTVkMTYtZTMzOC00OGM4LWJhZTYtYWU3YzJkMWFkZjk1In0sImlhdCI6MTY3NzY2ODgyMywiZXhwIjoxNjc4MjczNjIzfQ.NvPzJ001H5abNiO5NgmElmU32oB36iAOY_QQBmi8CmU
#11 user eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxMSwiZGVwZW5kc19vbiI6Miwicm9sZSI6eyJpZCI6NCwibmFtZSI6InVzZXIifSwidXNlcl90b2tlbiI6ImI1YWM2NTA2LTYyZGMtNDAwMi05NzJkLTk2YWIwMWVjN2NiNyJ9LCJpYXQiOjE2Nzc2Njg4MzcsImV4cCI6MTY3ODI3MzYzN30.1ZIPyS3MicxgkNdmdNOpE4sq-sa1O1WBeAwZUOSo8wM

GET http://localhost:8000/health

#GET http://localhost:8002/auth/bypass/1
GET https://questions.kennycallado.dev/auth/bypass/11
Accept: application/json

GET http://localhost:8000/api/v1/question
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxMSwiZGVwZW5kc19vbiI6Miwicm9sZSI6eyJpZCI6NCwibmFtZSI6InVzZXIifSwidXNlcl90b2tlbiI6ImI1YWM2NTA2LTYyZGMtNDAwMi05NzJkLTk2YWIwMWVjN2NiNyJ9LCJpYXQiOjE2Nzc2Njg4MzcsImV4cCI6MTY3ODI3MzYzN30.1ZIPyS3MicxgkNdmdNOpE4sq-sa1O1WBeAwZUOSo8wM

GET http://localhost:8000/api/v1/question/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxMSwiZGVwZW5kc19vbiI6Miwicm9sZSI6eyJpZCI6NCwibmFtZSI6InVzZXIifSwidXNlcl90b2tlbiI6ImI1YWM2NTA2LTYyZGMtNDAwMi05NzJkLTk2YWIwMWVjN2NiNyJ9LCJpYXQiOjE2Nzc2Njg4MzcsImV4cCI6MTY3ODI3MzYzN30.1ZIPyS3MicxgkNdmdNOpE4sq-sa1O1WBeAwZUOSo8wM

# as admin coord or thera
POST http://localhost:8000/api/v1/question
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxMSwiZGVwZW5kc19vbiI6Miwicm9sZSI6eyJpZCI6NCwibmFtZSI6InVzZXIifSwidXNlcl90b2tlbiI6ImI1YWM2NTA2LTYyZGMtNDAwMi05NzJkLTk2YWIwMWVjN2NiNyJ9LCJpYXQiOjE2Nzc2Njg4MzcsImV4cCI6MTY3ODI3MzYzN30.1ZIPyS3MicxgkNdmdNOpE4sq-sa1O1WBeAwZUOSo8wM
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxLCJkZXBlbmRzX29uIjoxLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4ifSwidXNlcl90b2tlbiI6IjBiZGJkZTk0LTY1ZjctNGVjMC1iNWI0LWMwYzE0ZDQ0MGEyZiJ9LCJpYXQiOjE2Nzc2Njg1NzAsImV4cCI6MTY3ODI3MzM3MH0.LyKLztGQ2rBMOlomvxoqDCJR9BmNi7UW0inp3rGYYu4
Content-Type: application/json

{
  "q_type": "range",
  "question": "What about the question?"
}

GET http://localhost:8000/api/v1/question/6
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxMSwiZGVwZW5kc19vbiI6Miwicm9sZSI6eyJpZCI6NCwibmFtZSI6InVzZXIifSwidXNlcl90b2tlbiI6ImI1YWM2NTA2LTYyZGMtNDAwMi05NzJkLTk2YWIwMWVjN2NiNyJ9LCJpYXQiOjE2Nzc2Njg4MzcsImV4cCI6MTY3ODI3MzYzN30.1ZIPyS3MicxgkNdmdNOpE4sq-sa1O1WBeAwZUOSo8wM

PUT http://localhost:8000/api/v1/question/6
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxMSwiZGVwZW5kc19vbiI6Miwicm9sZSI6eyJpZCI6NCwibmFtZSI6InVzZXIifSwidXNlcl90b2tlbiI6ImI1YWM2NTA2LTYyZGMtNDAwMi05NzJkLTk2YWIwMWVjN2NiNyJ9LCJpYXQiOjE2Nzc2Njg4MzcsImV4cCI6MTY3ODI3MzYzN30.1ZIPyS3MicxgkNdmdNOpE4sq-sa1O1WBeAwZUOSo8wM
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxLCJkZXBlbmRzX29uIjoxLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4ifSwidXNlcl90b2tlbiI6IjBiZGJkZTk0LTY1ZjctNGVjMC1iNWI0LWMwYzE0ZDQ0MGEyZiJ9LCJpYXQiOjE2Nzc2Njg1NzAsImV4cCI6MTY3ODI3MzM3MH0.LyKLztGQ2rBMOlomvxoqDCJR9BmNi7UW0inp3rGYYu4
Content-Type: application/json

{
  "q_type": "input",
  "question": "What about the question?"
}
