#
# export WORKING_URL=questions.kennycallado.dev
# export WORKING_URL=localhost:8000

# 1 admin 
# 2 coord 
# 4 thera 
# 7 user 
#11 user 

GET http://localhost:8000/health

#{{{ question

GET http://localhost:8000/api/v1/question
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/question/1
Accept: application/json
Authorization: Bearer 

# as admin coord or thera
POST http://localhost:8000/api/v1/question
Accept: application/json
Authorization: Bearer 
#Authorization: Bearer 
Content-Type: application/json

{
  "q_type": "range",
  "question": "What about the question?"
}

GET http://localhost:8000/api/v1/question/6
Accept: application/json
Authorization: Bearer 

PUT http://localhost:8000/api/v1/question/6
Accept: application/json
Authorization: Bearer 
#Authorization: Bearer 
Content-Type: application/json

{
  "q_type": "input",
  "question": "What about the question?"
}

#}}}

#{{{ form

GET http://localhost:8000/api/v1/form
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxLCJkZXBlbmRzX29uIjoxLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4ifSwidXNlcl90b2tlbiI6IjUyZTM3YzQzLTk1ZjMtNGM3YS1iN2Y1LTNkNjI4Zjc1MDJlNyJ9LCJpYXQiOjE2Nzc2ODYzNjQsImV4cCI6MTY3ODI5MTE2NH0.hgQR1PLuhb0wb8jky8FMhCv47Jo3NVnd2GryJ7G_VSU

GET http://localhost:8000/api/v1/form/4
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxLCJkZXBlbmRzX29uIjoxLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4ifSwidXNlcl90b2tlbiI6IjUyZTM3YzQzLTk1ZjMtNGM3YS1iN2Y1LTNkNjI4Zjc1MDJlNyJ9LCJpYXQiOjE2Nzc2ODYzNjQsImV4cCI6MTY3ODI5MTE2NH0.hgQR1PLuhb0wb8jky8FMhCv47Jo3NVnd2GryJ7G_VSU

# as admin coord or thera
POST http://localhost:8000/api/v1/form
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxLCJkZXBlbmRzX29uIjoxLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4ifSwidXNlcl90b2tlbiI6IjUyZTM3YzQzLTk1ZjMtNGM3YS1iN2Y1LTNkNjI4Zjc1MDJlNyJ9LCJpYXQiOjE2Nzc2ODYzNjQsImV4cCI6MTY3ODI5MTE2NH0.hgQR1PLuhb0wb8jky8FMhCv47Jo3NVnd2GryJ7G_VSU
#Authorization: Bearer 
Content-Type: application/json

{
  "name": "Form 5",
  "description": "More complex description",
  "questions_id": [ 1, 2 ]
}

GET http://localhost:8000/api/v1/form/5
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxLCJkZXBlbmRzX29uIjoxLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4ifSwidXNlcl90b2tlbiI6IjUyZTM3YzQzLTk1ZjMtNGM3YS1iN2Y1LTNkNjI4Zjc1MDJlNyJ9LCJpYXQiOjE2Nzc2ODYzNjQsImV4cCI6MTY3ODI5MTE2NH0.hgQR1PLuhb0wb8jky8FMhCv47Jo3NVnd2GryJ7G_VSU

PUT http://localhost:8000/api/v1/form/5
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIiLCJ1c2VyIjp7ImlkIjoxLCJkZXBlbmRzX29uIjoxLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4ifSwidXNlcl90b2tlbiI6IjUyZTM3YzQzLTk1ZjMtNGM3YS1iN2Y1LTNkNjI4Zjc1MDJlNyJ9LCJpYXQiOjE2Nzc2ODYzNjQsImV4cCI6MTY3ODI5MTE2NH0.hgQR1PLuhb0wb8jky8FMhCv47Jo3NVnd2GryJ7G_VSU
#Authorization: Bearer 
Content-Type: application/json

{
  "name": "Form 5",
  "description": "More complex description. Not really",
  "questions_id": [ 1, 2 ]
}

#}}}
