[default]
port        = 8000
secret_key  = "OQ6ORGl54R2iJFmsABI9+gQ84xC7j4nivkK+WVfrLBI="
profile_url = "http://localhost:8001/api/v1/profile"
uesr_url    = "http://localhost:8002/api/v1/user"

[default.databases.questions]
url = "postgres://forms:forms@localhost/forms"
